### ISSUE TITLE
Intro autoskip means that sometimes the intro cutscene skips too fast

### ISSUE THREAD

**Issue by samrambo2002** [AIESydneyStudents/CHEESEBALLS_STUDIOS#12]
Description: The intro cutscene can pass in a split second due to clicking too fast. Maybe add a small cooldown between clicking so that the player doesn't miss the story.

Also to note:
- Get rid of the click to continue (text on the second screen)
- Move text box so that the middle line of text isn't cut off by the white border
- Is there supposed to be dialogue in the intro cutscene? There is not any currently.

Priority: High

Build: 5-12-21

Reproduction: Click super fast when going through the cutscene.

**Comment by MayKovacs** [comment]
This is not a bug,, this is design advice.
