### ISSUE TITLE
Blue lighting in choosing scene and map scene (intro scene and map scene)

### ISSUE THREAD

**Issue by samrambo2002** [AIESydneyStudents/CHEESEBALLS_STUDIOS#14]
Description: Graphical error of blue light shows up in all scenes

Priority: high

Build: 5-12-21

Reproduction: Playing through the entire game, every scene is blue tinged.

**Comment by MayKovacs** [comment]
Blue lighting is fixed. The issue was in project settings where m_ActiveColorSpace: 0, when it should be m_ActiveColorSpace: 1.
