### ISSUE TITLE
Bug with blue fetch quest

### ISSUE THREAD

**Issue by samrambo2002** [AIESydneyStudents/CHEESEBALLS_STUDIOS#17]
Description: When playing the blue fetch quest component of the game, the dialogue choice "Is there something we can do" skips through two dialogue boxes fast and then kicks the player back to the main menu.

Priority: low

Build: 5-12-21

Reproduction: 
1. Meet all three characters at least once
2. Travel to the cave scene
3. Choose "Is there something we can do?" as an option.

**Comment by MayKovacs** [comment]
#17 Closed
