### ISSUE TITLE
When using the {wc} command inside textboxes that spill over the portraits do not show up

### ISSUE THREAD

**Issue by samrambo2002** [AIESydneyStudents/CHEESEBALLS_STUDIOS#20]
Description: At certain points in dialogue, such as the Swiss dialogue: 

"The cheese can be eaten as a table cheese, being eaten on your typical sandwich or on a cheese platter {wc} but is also a great cheese to be melted and served, being a nice creamy melt thanks to a good high-water content in most Gruyere cheeses." 

We added {wc} to make the text spill over. An unintentional side effect being that portraits disappear when this is added.

Priority: Low, due to the amount of work to go through and remove or replace this command.

Build: 5-12-21

Reproduction: Go to the mansion scene when you go past the intro scene and map scene.

**Comment by MayKovacs** [comment]
#20 Closed, #21 is a better description of this bug, and wc does not seem to be a factor.
